# Generated by Django 3.2.9 on 2021-11-30 17:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_rename_dateposted_post_date_posted'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='date_posted',
            new_name='datePosted',
        ),
    ]
